version: '3.8'

services:
  gmail-mcp-server:
    build: .
    container_name: gmail-mcp-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      # Add your environment variables here or use .env file
      # - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    env_file:
      - .env
    networks:
      - mcp-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gmail-mcp.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.gmail-mcp.entrypoints=websecure"
      - "traefik.http.routers.gmail-mcp.tls.certresolver=letsencrypt"
      - "traefik.http.services.gmail-mcp.loadbalancer.server.port=8080"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/mcp"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mcp-network:
    driver: bridge 